### ISSUE TITLE
Support for smalldatetime

### ISSUE THREAD

**Issue by wborowiecki** [Avanade/DbEx#23]
When using nTangle I'm getting the following error when trying to generate code for a table that contains "smalldatatime". Please add support for it.

System.InvalidOperationException: 'Database data type 'smalldatetime' does not have corresponding .NET type mapping defined.'

**Comment by chullybun** [comment]
This has been resolved in the latest version. See https://github.com/Avanade/DbEx/blob/f88e2542753387cc422d5e13c0ce2a152ada9c3c/src/DbEx/Schema/DbTypeMapper.cs#L55
