### ISSUE TITLE
Invalid comment or missing functionality?

### ISSUE THREAD

**Issue by karpikpl** [Avanade/DbEx#7]
https://github.com/Avanade/DbEx/blob/6142d380718f84cd18d8e37b0d4e3b6690e22297/src/DbEx/Migration/DatabaseMigratorBase.cs#L366-L379

Line 366 mentions `.sql` files but 379 looks for `.yml` and `.yaml`

**Comment by karpikpl** [comment]
looks like that feature is not there.

it would be useful to either:
1. support SQL files for `data` command, OR
2. support SQL files for `execute` command 

@chullybun  what do you think makes more sense?

**Comment by chullybun** [comment]
Hi @karpikpl. The code above is correct, the comments are incorrect - YAML is the intended. I had not considered supporting executing `.sql` for the two scenarios you suggest - those are great ideas and will look to add.

**Comment by chullybun** [comment]
@karpikpl - I have just published `v1.0.2` NuGet package. Support for SQL files added as described above.
